[project]
name = "code-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.65.2",
    "python-dotenv>=1.0.1",
    "qdrant-client>=1.13.2",
    "semantic-text-splitter>=0.24.1",
    "transformers>=4.49.0",
    "tree-sitter>=0.24.0",
    "tree-sitter-css>=0.23.2",
    "tree-sitter-go>=0.23.4",
    "tree-sitter-html>=0.23.2",
    "tree-sitter-java>=0.23.5",
    "tree-sitter-javascript>=0.23.1",
    "tree-sitter-markdown>=0.3.2",
    "tree-sitter-python>=0.23.6",
    "tree-sitter-typescript>=0.23.2",
    "tree-sitter-xml>=0.7.0",
    "tree-sitter-yaml>=0.7.0",
]
